# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.


In [5]:
#### 1. Import the numpy package under the name `np` (★☆☆)
#### hint: import … as
import numpy as np

In [7]:
#### 2. Create a null vector of size 10 (★☆☆)
#### `hint: np.zeros`
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#### `hint: array[4]`
a = np.zeros(10)
a

a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [24]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
####`hint: arange`

a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [34]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
####`hint: reshape`

np.random.randint(0, 9, (3, 3))

array([[8, 6, 4],
       [3, 0, 4],
       [6, 8, 1]])

In [38]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#### `hint: np.nonzero`

a = [1, 2, 0, 0, 4, 0]
np.nonzero(a)

(array([0, 1, 4]),)

In [39]:
#### 7. Create a 3x3 identity matrix (★☆☆)
#### `hint: np.eye`

np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
#### `hint: np.random.random`

a = np.random.random((3,3,3))
a

array([[[0.72175532, 0.29187607, 0.91777412],
        [0.71457578, 0.54254437, 0.14217005],
        [0.37334076, 0.67413362, 0.44183317]],

       [[0.43401399, 0.61776698, 0.51313824],
        [0.65039718, 0.60103895, 0.8052232 ],
        [0.52164715, 0.90864888, 0.31923609]],

       [[0.09045935, 0.30070006, 0.11398436],
        [0.82868133, 0.04689632, 0.62628715],
        [0.54758616, 0.819287  , 0.19894754]]])

In [67]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#### `hint: min, max`

a = np.random.random((10,10))
a

array([[0.83471509, 0.36698733, 0.51538211, 0.47237913, 0.38615209,
        0.744137  , 0.33524208, 0.59543829, 0.31613338, 0.34625042],
       [0.24483181, 0.69795016, 0.21208083, 0.26729317, 0.37389408,
        0.57308851, 0.91735808, 0.81897594, 0.16318089, 0.02415477],
       [0.78465363, 0.26485738, 0.33936706, 0.81436959, 0.80745472,
        0.49356164, 0.84531244, 0.36518998, 0.0478309 , 0.26414579],
       [0.46386716, 0.69335506, 0.31343675, 0.46253679, 0.81968765,
        0.68449103, 0.32403382, 0.576812  , 0.63264998, 0.59646167],
       [0.13782688, 0.61800102, 0.49346369, 0.14361212, 0.03082189,
        0.93915573, 0.25683772, 0.0571346 , 0.38770822, 0.35709675],
       [0.98638414, 0.93959064, 0.58277522, 0.99310313, 0.9899145 ,
        0.86505637, 0.16171823, 0.36849024, 0.30672666, 0.34086324],
       [0.29047775, 0.63786407, 0.050654  , 0.93518431, 0.02584484,
        0.53163905, 0.07160379, 0.69149444, 0.11708751, 0.19351251],
       [0.9123815 , 0.31071241, 0.3156425

In [68]:
a.min()

0.015456051150818495

In [69]:
a.max()

0.9931031337764241

In [58]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
#### `hint: mean`

a = np.random.random(30)
print(a)

[0.64414354 0.38074849 0.66304791 0.16365073 0.96260781 0.34666184
 0.99175099 0.2350579  0.58569427 0.4066901  0.13623432 0.54413629
 0.51817635 0.76685511 0.93385014 0.08970338 0.19577126 0.99419368
 0.2351805  0.23898637 0.62909983 0.73495258 0.68834438 0.03113075
 0.90251384 0.28643533 0.55561256 0.37642024 0.02662436 0.49414912]


In [59]:
a.mean()

0.4919474657842404

In [103]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#### `hint: np.diag`

a = np.diag(1+np.arange(4),k=-1)
print(a)
####np.diagonal(a).copy() 

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [104]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#### `hint: (x -mean)/std`

a = np.random.random((5,5))
a = (a - np.mean (a)) / (np.std (a))
print(a)

[[-0.58773932 -0.58779388 -0.7429984  -1.50826384 -0.7730286 ]
 [-0.71261195  1.36150329  0.78071707 -0.95946004  1.58466107]
 [-1.74076265 -0.827669    0.57512727 -0.27121085  0.34784011]
 [-1.18516618  0.67771133  1.51976691 -1.14930823  0.49063663]
 [-0.19937683  1.34770302  1.05250917  1.20433809  0.30287578]]


In [113]:
#### 13. How to find common values between two arrays? (★☆☆)
#### `hint: np.intersect1d`

a = np.random.randint(0,15,10)
b = np.random.randint(0,16,17)
print(a)
print(b)
print(np.intersect1d(a,b))

[ 4  3  0  7 10  4  2 13  8 11]
[ 6  3  4  9 10 14  8 10  2  1 15 15  6  6 11 11  4]
[ 2  3  4  8 10 11]


In [114]:
### 14. Create a random vector of size 10 and sort it (★★☆)
#### `hint: sort`

a= np.random.random(10)
print(a)

a.sort()
print(a)

[0.33522007 0.68349518 0.40582838 0.57773443 0.91131418 0.12562148
 0.87867396 0.61240462 0.37508527 0.25476774]
[0.12562148 0.25476774 0.33522007 0.37508527 0.40582838 0.57773443
 0.61240462 0.68349518 0.87867396 0.91131418]


In [115]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#### `hint: argmax`

a = np.random.random(10)
print(a)
a[a.argmax()] = 0
print(a)

[0.5972063  0.53084104 0.64835134 0.65834472 0.70896881 0.05331874
 0.34169806 0.89187021 0.995295   0.99329348]
[0.5972063  0.53084104 0.64835134 0.65834472 0.70896881 0.05331874
 0.34169806 0.89187021 0.         0.99329348]


In [116]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
#### `hint: mean(axis=,keepdims=)`

a = np.random.rand(5, 10)
print(a)
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[0.39669248 0.06980398 0.37826257 0.81505315 0.8050386  0.1027827
  0.86972896 0.55063662 0.16622097 0.36603653]
 [0.60653312 0.26016318 0.19145641 0.69752299 0.54467498 0.9029689
  0.84620273 0.96684628 0.15107294 0.57521624]
 [0.94238783 0.14996386 0.06535428 0.16276314 0.25870904 0.88367752
  0.95247782 0.57409507 0.8675513  0.39484458]
 [0.61669622 0.78287996 0.15812862 0.69665603 0.42507369 0.81567578
  0.35797706 0.25891973 0.54812287 0.18888446]
 [0.39815483 0.62460583 0.51551477 0.83965739 0.41398623 0.68586388
  0.90650652 0.4942967  0.78559078 0.29720543]]
[[-0.05533317 -0.38222167 -0.07376309  0.36302749  0.35301294 -0.34924295
   0.41770331  0.09861097 -0.28580469 -0.08598913]
 [ 0.03226734 -0.3141026  -0.38280936  0.12325721 -0.02959079  0.32870312
   0.27193695  0.3925805  -0.42319284  0.00095046]
 [ 0.41720539 -0.37521859 -0.45982816 -0.3624193  -0.26647341  0.35849508
   0.42729538  0.04891263  0.34236885 -0.13033786]
 [ 0.13179477  0.29797852 -0.32677282  0.21175459 -

In [117]:
#### 17. How to get the n largest values of an array (★★★)
#### hint: np.argsort | np.argpartition`

Z = np.arange(10000)
print(Z)

np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[   0    1    2 ... 9997 9998 9999]
[9995 9996 9997 9998 9999]
[9997 9996 9998 9999 9995]


In [120]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
####`hint: np.where`

a = np.random.random((5,3))
print(a)
####a = np.arange(9).reshape(5, 3)
####print(a)

[[0.515199   0.82615201 0.379956  ]
 [0.0302302  0.53080606 0.20299532]
 [0.89228758 0.79054695 0.13223287]
 [0.0094548  0.30786644 0.42368822]
 [0.91177289 0.58645325 0.83965614]]
